<?php
$translate = $this->plugin('translate');
?>
<form id="advanced-search-modal" method="get" action="<?php echo $this->escapeHtml($this->url('site/resource', ['controller' => 'item', 'action' => 'browse'], true)); ?>">
  <?php echo $this->partial('common/advanced-search', ['query' => $this->params()->fromQuery(), 'resourceType' => 'item']); ?>
  <div id="page-actions">
      <button type="submit" name="submit" class="btn btn-secondary mt-3" value="<?php echo $this->escapeHtml($translate('Search')); ?>"><?php echo $this->escapeHtml($translate('Search')); ?></button>
  </div>
</form>
