<?php
/* @var $container Zend\Navigation\Navigation */
$container = $this->container;
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<ul class="nav col-12 col-md-auto justify-content-center justify-content-md-start mb-2 mb-md-0">
  <?php foreach ($container as $page): ?>
    <?php if (!$this->navigation()->accept($page)) {
      continue;
    } ?>
    <?php /* @var $page Laminas\Navigation\Page\Mvc */ ?>
    <?php $hasChildren = $page->hasPages() ?>
    <?php if (!$hasChildren || ($page->getLabel() == 'Exhibits')): ?>
      <li class="nav-item">
        <a class="nav-link link-dark <?php echo $page->isActive() ? 'active' : ''; ?>" <?php echo $page->isActive() ?
                                                                                          'aria-current="page"' : ''; ?> href="
      <?php echo $page->getHref() ?>">
          <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
        </a>
      </li>
    <?php else: ?>
      <?php
      //check if access is allowed at least one item
      $access = false;
      foreach ($page->getPages() as $child) {
        if ($this->navigation()->accept($child) && $child->get("separator") !== true) {
          $access = true;
        }
      }
      if ($access):
      ?>
        <li class="nav-item dropdown">
          <?php $idName = str_replace(' ', '', $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain()))); ?>
          <a class="nav-link text-dark dropdown-toggle" id="<?php echo $idName; ?>" href="#" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            <?php echo $this->escapeHtml($this->translate($page->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
            <b class="caret"></b>
          </a>
          <?php echo $this->partial('common/bootstrap-subnavigation.phtml', ['container' => $container, 'children' => $page->getPages(), 'level' => 1, 'idName' => $idName]); ?>
        </li>
      <?php endif; ?>
    <?php endif ?>
  <?php endforeach ?>
</ul>