<ul class="dropdown-menu" aria-labelledby="<?php echo $idName; ?>">
  <?php foreach ($children as $child): ?>
  <?php $hasChildren = $child->hasPages() ?>
  <?php if (!$this->navigation()->accept($child)) {
        continue;
      } ?>
  <?php if (!$hasChildren): ?>
  <li>
    <a href="<?php echo $child->getHref() ?>" class="dropdown-item <?php echo $child->isActive() ? 'active' : ''; ?>">
      <?php echo $this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
    </a>
  </li>
  <?php else: ?>
  <?php
        //check if access is allowed at least one item
        $access = false;
        foreach ($child->getPages() as $grandChild) {
          if ($this->navigation()->accept($grandChild) && $grandChild->get("separator") !== true) {
            $access = true;
          }
        }
        if ($access):
        ?>
  <li class="nav-item dropdown-submenu">
    <?php $idName = str_replace(' ', '', $this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain()))); ?>
    <a class="nav-link dropdown-toggle" id="<?php echo $idName; ?>" href="#" role="button" data-bs-toggle="dropdown"
      aria-expanded="false">
      <?php echo $this->escapeHtml($this->translate($child->getLabel(), $this->navigation($container)->getTranslatorTextDomain())); ?>
      <b class="caret"></b>
    </a>
    <?php echo $this->partial('common/bootstrap-subnavigation.phtml', ['container' => $container, 'children' => $child->getPages(), 'level' => ($level + 1), 'idName' => $idName]); ?>
  </li>

  <?php endif; ?>
  <?php endif; ?>
  <?php endforeach ?>
</ul>