<?php
$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
?>
<nav class="pagination" role="navigation">
<?php if ($totalCount): ?>
  <li class="nav-item">
    <form method="GET" action="">
      <?php echo $this->queryToHiddenInputs(['page']); ?>
      <div class="row">
        <?php if ($currentPage != 1): ?>
        <?php
        $prevIcon = '
        <i class="fas fa-angle-left" aria-hidden="true" title="' . $translate("Previous") . '">
          <span class="visually-hidden">' . $translate("Previous") . '</span>
        </i>
        ';
        ?>
        <div class="col-auto">
          <?php echo $hyperlink->raw($prevIcon, $previousPageUrl, ['class' => 'previous o-icon-prev button btn btn-secondary', 'title' => $translate('Previous'), 'aria-label' => $translate('Previous')]); ?>
        </div>
        <?php endif; ?>
        <div class="col-auto">
          <input type="text" name="page" class="page-input-top form-control" value="<?php echo $currentPage; ?>" size="4" <?php echo ($pageCount == 1) ? 'readonly' : ''; ?> aria-label="<?php echo $translate('Page'); ?>">
        </div>
        <div class="col-auto p-0">
          <div class="page-count col-form-label"><?php echo sprintf($translate('of %s'), $pageCount); ?></div>
        </div>
        <?php if ($currentPage < $pageCount): ?>
        <?php
        $nextIcon = '
        <i class="fas fa-angle-right" aria-hidden="true" title="' . $translate("Next") . '">
          <span class="visually-hidden">' . $translate("Next") . '</span>
        </i>
        ';
        ?>
        <div class="col-auto">
          <?php echo $hyperlink->raw($nextIcon, $nextPageUrl, ['class' => 'next o-icon-next button btn btn-secondary', 'title' => $translate('Next'), 'aria-label' => $translate('Next')]); ?>
        </div>
        <?php endif; ?>
      </div>
      <?php
      $from = $offset + 1;
      $to = ($currentPage < $pageCount) ? $offset + $perPage : $totalCount;
      ?>
      <div class="row justify-content-center mt-2">
        <div class="col-auto">
          <div class="row-count col-form-label"><?php echo sprintf($translate('(results %1$s–%2$s of %3$s)'), $from, $to, $totalCount); ?></div>
        </div>
      </div>
    </form>
  </li>
<?php endif; ?>
</nav>
