<?php
$translate = $this->plugin('translate');
?>

<div class="container pt-md-2 pb-3">
    <div class="row">
        <div class="container" id="error-container">
            <div class="row">
                <div class="col-12" id="error">
                    <?php echo $this->pageTitle($translate('403 Forbidden'), 2); ?>
                    <p class="lead">You do not have permission to access this page. Please contact us directly at <a
                            href="mailto:archiveondemand@fitnyc.edu">archiveondemand@fitnyc.edu</a> for more
                        information.</p>
                    <?php if (ini_get('display_errors')): ?>
                        <h3>Stace Trace</h3>
                        <pre>
                                                    <?php echo $this->exception; ?>
                                                    </pre>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>