<?php
$translate = $this->plugin('translate');
$item = $media->item();

$this->htmlElement('body')->appendAttribute('class', 'media resource show'); ?>

<?php $this->trigger('view.show.before'); ?>

<div class="container pt-4 pb-5">
  <div class="row justify-content-center">
    <div class="col">
      <?php echo $this->pageTitle($media->displayTitle(), 2); ?>
      <h3><?php echo $translate('Media'); ?></h3>
      <p class="media-parent-item">
          <?php echo sprintf($translate('Part of %s'), $item->link($item->displayTitle())); ?>
      </p>
      <?php echo $media->render(); ?>
      <?php echo $media->displayValues(); ?>
    </div>
  </div>
</div>



<?php $this->trigger('view.show.after'); ?>
