<?php
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->pageTitle($this->page->title(), 1);
if ((strtolower($this->page->title()) == "home") && ($summary = $this->site->summary())) {
  $this->headMeta()->appendName('description', nl2br($this->escapeHtml($summary)));
}
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>

<?php
$nav = $this->site->publicNav();
$container = $nav->getContainer();
$activePage = $nav->findActive($container);
if ($activePage):
?>
  <?php if ($activePage['depth'] !== 0): ?>
    <nav class="breadcrumbs">
      <?php echo $nav->breadcrumbs(); ?>
    </nav>
  <?php endif; ?>
<?php endif; ?>

<?php if ($activePage): ?>
  <?php if ($this->displayNavigation && $activePage['page']->hasPages()): ?>
    <nav class="sub-menu">
      <?php echo $nav->menu()->renderSubMenu(); ?>
    </nav>
  <?php endif; ?>
<?php endif; ?>

<?php $this->trigger('view.show.before'); ?>
<?php if ((strtolower($this->page->title()) == 'home') || (strtolower($this->page->title()) == 'homepage')): ?>
  <h1 class="visually-hidden">FIT SPARC Digital Homepage</h1>
<?php else: ?>
  <div class="container-fluid py-3">
    <h1>
      <?php echo $this->page->title(); ?>
    </h1>
  </div>
<?php endif; ?>
<?php echo $this->content; ?>
<?php $this->trigger('view.show.after'); ?>
<?php if ($showPagePagination): ?>
  <?php echo $this->sitePagePagination(); ?>
<?php endif; ?>