<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$site = $this->currentSite();
$siteID = $site->id();
$siteSlug = $site->slug();
$useSolr = $this->getHelperPluginManager()->has('getSearchFormForSite');
$user = $this->identity();
$grid = 'row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-xl-4';
if ($this->resourceType == "item-set") {
  $grid = 'row-cols-1 row-cols-lg-2 row-cols-xl-3 row-cols-xxl-4';
}
$ratio = ($this->resourceType == "item-set") ? "ratio ratio-21x9" : "";
?>

<div id="grid" class="container-fluid my-4 my-lg-5 <?php echo $this->resourceType; ?>">
  <?php if ($this->heading): ?>
    <h2 class="mb-4 mb-lg-5"><?php echo $this->heading; ?></h2>
  <?php endif; ?>
  <div class="row <?php echo $grid; ?> align-items-center" id="grid-row">
    <?php
    foreach ($resources as $resource):
      $title = $resource->displayTitle();
      if (($this->resourceType == "item-set") && $useSolr) {
        $url = $this->url('site/search', ['site-slug' => $siteSlug], ['query' => ['item_set_id' => [$resource->id()]]]);
      } else {
        $url = $resource->url();
      }
      if ($this->resourceType == "item-set") {
        $restricted = false;
        foreach ($resource->value('dcterms:accessRights', ['all' => true, 'type' => 'literal']) as $accessRight) {
          if (str_contains(strtolower($accessRight), strtolower("Restricted to members of the FIT Community"))) {
            $restricted = true;
            break;
          }
        }
        if (!$user && $restricted) {
          $count = "Restricted access";
        } else {
          $count = $this->api()->search('items', ['item_set_id' => $resource->id(), 'site_id' => $siteID, 'limit' => 0])->getTotalResults() . " items";
        }
      }

    ?>
      <div class="col grid-item-container">
        <div class="card border-0 grid-item bg-transparent">
          <a href="<?php echo $url; ?>" class="card-img rounded-0 <?php echo $ratio; ?>" title="<?php echo $title; ?>">
            <?php echo $this->thumbnail($resource, 'medium', ['class' => 'w-100 rounded-0 border border-2 border-white object-fit-cover', 'alt' => $title]); ?>
          </a>
          <div class="card-body">
            <h3 class="grid-item-title">
              <a href="<?php echo $url; ?>" class="text-dark text-decoration-none" title="<?php echo $title; ?>">
                <?php echo $title; ?>
              </a>
            </h3>
            <?php if ($this->resourceType == "item-set"): ?>
              <div class="item-count collection-types">
                <span class="fst-italic">
                  <?php echo $count; ?>
                </span>
                <?php echo $this->CollectionIconHelper($resource); ?>
              </div>
            <?php endif; ?>
          </div>
        </div>
      </div>
    <?php endforeach; ?>
  </div>
  <?php if ($this->linkText): ?>
    <div class="row justify-content-end">
      <div class="col-auto">
        <?php
        if ($this->linkText) {
          if ($solrLink && $useSolr) {
            $url = $solrLink;
          } else {
            $query = $this->query;
            // Add page to item-sets so pagination works correctly
            if ($this->resourceType == "item-set") {
              $query['page'] = 1;
            }
            $url = $this->url(
              'site/resource',
              ['controller' => $this->resourceType, 'action' => 'browse'],
              ['query' => $query],
              true
            );
          }
          echo $this->hyperlink(
            $this->linkText,
            $url,
            ['class' => 'btn btn-outline-dark rounded-0 border-2 mt-3']
          );
        }
        ?>
      </div>
    </div>
  <?php endif; ?>
</div>