<?php
$this->headLink()->appendStylesheet('https://cdn.jsdelivr.net/npm/glider-js@1.7.7/glider.min.css', 'screen', null, ['integrity' => 'sha256-o2HrB5EL5AdkNI2+9n8NzI0p6VflIDQiimYGrayGE30=', 'crossorigin' => 'anonymous']);
$this->headLink()->appendStylesheet($this->assetUrl('css/browse-preview-carousel.css', 'FITModule'));
$this->headScript()->appendFile('https://cdn.jsdelivr.net/npm/glider-js@1.7.7/glider.min.js', 'text/javascript', ['integrity' => 'sha256-3/0U+/cLec+S2/6Gu2VYTzbA/2gaBACu5f7fGacrvAY=', 'crossorigin' => 'anonymous']);
$this->headScript()->appendFile($this->assetUrl('js/browse-preview-carousel.js', 'FITModule'));
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<div class="container-fluid browse-preview">
    <?php if ($this->heading || $filter): ?>
        <div class="row align-items-center mb-3 browse-header">
            <?php if ($this->heading): ?>
                <div class="col-auto">
                    <h2 class="mb-0">
                        <?php echo $this->heading; ?>
                    </h2>
                </div>
            <?php endif; ?>
            <?php if ($filter): ?>
                <?php // check if solr/search module is activated by checking if the helper is present        
                ?>
                <?php if ($this->getHelperPluginManager()->has('getFacetsForBrowse')): ?>
                    <?php $facetsForBrowse = $this->getFacetsForBrowse($searchQuery, null); ?>
                    <?php if ($facetsForBrowse && $facetsForBrowse['facets']): ?>
                        <div class="col-auto">
                            <!-- filter  -->
                            <button id="filter-button" class="btn btn-fit-green floating-action icon-only" type="button"
                                data-bs-toggle="offcanvas" data-bs-target="#searchFilters" aria-controls="searchFilters"
                                aria-label="Filter results">
                                <span class="action-container">
                                    <i class="fas fa-filter" aria-hidden="true" title="Filter results">
                                    </i>
                                </span>
                            </button>
                            <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="searchFilters"
                                aria-labelledby="searchFiltersLabel">
                                <div class="offcanvas-header border-bottom">
                                    <h3 class="offcanvas-title" id="searchFiltersLabel">
                                        <?php echo $this->translate('Search Filters'); ?>
                                    </h3>
                                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"
                                        aria-label="Close"></button>
                                </div>
                                <div class="offcanvas-body p-0">
                                    <?php echo $this->partial('search/facets', ['facets' => $facetsForBrowse['facets'], 'dateFacetStats' => $facetsForBrowse['dateFacetStats'], 'queryParams' => []]); ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>


    <div class="row align-items-center justify-content-around">

        <div class="col-auto order-first pe-0 d-none d-sm-block">
            <button class="btn-arrow btnPrevious ps-0 border-0 bg-transparent text-secondary" type="button"
                aria-label="Previous">
                <i class="fas fa-chevron-left" aria-hidden="true" title="Previous">
                </i>
            </button>
        </div>
        <div class="col-auto order-last ps-0 d-none d-sm-block">
            <button class="btn-arrow btnNext pe-0 border-0 bg-transparent text-secondary" type="button"
                aria-label="Next">
                <i class="fas fa-chevron-right" aria-hidden="true" title="Next">
                </i>
            </button>
        </div>
        <div class="col overflow-hidden px-0">
            <div class="glider">
                <?php
                $headingTerm = $this->siteSetting('browse_heading_property_term');
                $filterLocale = (bool) $this->siteSetting('filter_locale_values');
                $lang = $this->lang();

                foreach ($this->resources as $resource):
                    $heading = $headingTerm ? $resource->value($headingTerm, ['default' => $translate('[Untitled]')]) : $resource->displayTitle(null, ($filterLocale ? $lang : null));
                ?>
                    <div class="card border-0 px-sm-3 px-xl-4">
                        <?php echo $resource->linkRaw($this->thumbnail($resource, 'medium', ['class' => 'browse-thumbnail shadow-sm', 'alt' => $heading], false), null, ['class' => 'card-img', 'title' => $heading]); ?>
                        <div class="card-body overflow-hidden">
                            <h3 class="resource-title">
                                <?php echo $resource->link($heading, null, ['class' => 'text-dark text-decoration-none', 'title' => $heading]); ?>
                            </h3>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?php
    if ($this->linkText):
        if ($solrLink && ($this->getHelperPluginManager()->has('getSearchFormForSite'))) {
            $url = $solrLink;
        } else {
            $query = $this->query;
            // Add page to item-sets so pagination works correctly
            if ($this->resourceType == "item-set") {
                $query['page'] = 1;
            }
            $url = $this->url(
                'site/resource',
                ['controller' => $this->resourceType, 'action' => 'browse'],
                ['query' => $query],
                true
            );
        }
        $query = $this->query;
        $query["page"] = 1;
        echo $this->hyperlink(
            $this->linkText,
            $url,
            ['class' => 'float-end me-sm-5 fw-bold text-decoration-none']
        );
    endif;
    ?>
</div>