<?php
$escape = $this->plugin('escapeHtml');
?>
<div id="landing-jumbotron" class="p-4 p-sm-5">
    <div id="landing-jumbotron-text" class="container p-4 p-sm-5 border border-black border-2">
        <div class="row justify-content-center">
            <div class="col-lg-11 col-xl-9 col-xxl-8">
                <hgroup class="text-center">
                    <h2>
                        <?php echo $escape($this->pageTitle); ?>
                    </h2>
                </hgroup>
            </div>
        </div>

    </div>
</div>