[info]
name = "FIT SPARC Digital"
version = "1.0.0"
author = "FIT Digital Initiatvies"
description = "Omeka-S theme for the FIT SPARC Digital. Built upon Bootstrap framework. Works with FITModule, and FIT-forked Solr modules, and FIT-forked MetadataBrowse."
;theme_link = ""
author_link = "https://github.com/fitnycdigitalinitiatives"
omeka_version_constraint = "^4.0.0"
helpers[] = "ItemDetailsHelper"
helpers[] = "CollectionIconHelper"
helpers[] = "CitationHelper"
helpers[] = "QueryToStringHelper"
helpers[] = "SocialShare"

[config]
page_templates.exhibit = "Exhibit"
page_templates.exhibit_browse = "Exhibit Browse"
page_templates.about = "About"