<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$this->htmlElement('html')->appendAttribute('lang', $this->lang())->appendAttribute('class', 'h-100');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->site->title())->setSeparator(' · ');
$this->headLink(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => $this->assetUrl('img/favicon.ico')], 'PREPEND')
  ->prependStylesheet($this->assetUrl('css/style.css'))
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css')
  ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.0/nouislider.css', 'screen', null, ['integrity' => 'sha512-MKxcSu/LDtbIYHBNAWUQwfB3iVoG9xeMCm32QV5hZ/9lFaQZJVaXfz9aFa0IZExWzCpm7OWvp9zq9gVip/nLMg==', 'crossorigin' => 'anonymous'])
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/css/all.min.css', 'screen', null, ['integrity' => 'sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4=', 'crossorigin' => 'anonymous'])
  ->prependStylesheet('https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css', 'screen', null, ['integrity' => 'sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT', 'crossorigin' => 'anonymous']);
$this->headScript()
  ->prependFile($this->assetUrl('js/advanced-search.js', 'Omeka'))
  ->prependFile($this->assetUrl('js/theme.js'))
  ->prependFile($this->assetUrl('js/global.js', 'Omeka'))
  ->prependFile('https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js')
  ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/15.6.0/nouislider.min.js', 'text/javascript', ['integrity' => 'sha512-1mDhG//LAjM3pLXCJyaA+4c+h5qmMoTc7IuJyuNNPaakrWT9rVTxICK4tIizf7YwJsXgDC2JP74PGCc7qxLAHw==', 'crossorigin' => 'anonymous'])
  ->prependFile('https://unpkg.com/infinite-scroll@4.0.1/dist/infinite-scroll.pkgd.min.js', 'text/javascript')
  ->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js', 'text/javascript', ['integrity' => 'sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO', 'crossorigin' => 'anonymous'])
  ->prependFile('https://code.jquery.com/jquery-3.6.0.min.js', 'text/javascript', ['integrity' => 'sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=', 'crossorigin' => 'anonymous']);
$this->trigger('view.layout');
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>
  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-HN7LCC8ZDL"></script>
  <script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
      dataLayer.push(arguments);
    }
    gtag('js', new Date());

    gtag('config', 'G-HN7LCC8ZDL');
  </script>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->headStyle(); ?>
  <?php echo $this->headScript(); ?>
</head>

<?php echo $this->htmlElement('body')->appendAttribute('class', 'd-flex flex-column h-100'); ?>
<a class="visually-hidden-focusable" href="#content">
  <?php echo $this->translate('Skip to main content'); ?>
</a>
<div class="flex-shrink-0">
  <header id="main-header" class="container-fluid d-flex flex-wrap align-items-center justify-content-lg-between pt-4 pb-5 py-sm-5">
    <a class="d-flex col-12 col-xl align-items-center mb-0 link-body-emphasis text-decoration-none brand" href="<?php echo $this->site->url(); ?>">
      <img src="<?php echo $this->assetUrl('img/new-sparc-digital-3d.png'); ?>"
        alt="FIT SPARC Digital">
    </a>
    <div class="d-flex flex-wrap col-12 col-xl-auto align-items-center mt-md-2 mt-xl-0">
      <?php echo $this->site->publicNav()->menu()->renderPartialWithParams(['site' => $this->site,], null, 'common/bootstrap-navigation.phtml'); ?>
      <div id="basic-search-col" class="col-12 col-md ms-md-2 position-relative">
        <?php if (($this->getHelperPluginManager()->has('getSearchFormForSite') && ($searchForm = $this->getSearchFormForSite($this->site, 'search/form/search-with-adv-modal')))): ?>
          <?php echo $searchForm; ?>
        <?php else: ?>
          <?php echo $this->partial('common/search-form'); ?>
        <?php endif; ?>
      </div>
    </div>
    <?php echo $this->userBar('common/theme-site-slug-as-domain-user-bar'); ?>
  </header>
</div>
<div class="flex-grow-1" id="content" role="main">
  <?php echo $this->content; ?>
</div>
<footer class="footer mt-auto py-4 py-md-5 border-top border-dark border-2">
  <div class="container-fluid text-center">
    <div class="row justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-5">
        <a href="https://www.fitnyc.edu">
          <img class="mb-3" src="<?php echo $this->assetUrl('img/wordmark-black-1-line.png'); ?>" alt="FIT SUNY Logo"
            id="fit-logo">
        </a>
        <p>
          ©
          <?php echo date("Y"); ?> Fashion Institute of Technology
          <br>
          All rights reserved.
        </p>
        <p class="text-left">This site is an initiative of the FIT Library.</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a class="link-dark" href="https://www.fitnyc.edu/academics/library/"
              aria-label="FIT Library Homepage"><i class="fas fa-home" aria-hidden="true"
                title="FIT Library Homepage"></i><span class="sr-only">FIT Library Homepage</span></a></li>
          <li class="list-inline-item"><a class="link-dark" href="https://www.facebook.com/FITLibrary"
              aria-label="FIT Library Facebook"><i class="fab fa-facebook" aria-hidden="true"
                title="FIT Library Facebook"></i><span class="sr-only">FIT Library Facebook</span></a></li>
          <li class="list-inline-item"><a class="link-dark" href="https://x.com/FITLibrary"
              aria-label="FIT Library X">
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" style="width: 1em;height: 1em;vertical-align: -0.125em;"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.-->
                <path fill="currentColor" d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z" />
              </svg>
              <span class="sr-only">FIT Library X</span></a></li>
          <li class="list-inline-item"><a class="link-dark" href="https://www.tiktok.com/@fitnyclibrary"
              aria-label="FIT Library TikTok"><i class="fab fa-tiktok" aria-hidden="true"
                title="FIT Library TikTok"></i><span class="sr-only">FIT Library TikTok</span></a></li>
          <li class="list-inline-item"><a class="link-dark" href="https://www.instagram.com/fitnyclibrary/"
              aria-label="FIT Library Instagram"><i class="fab fa-instagram" aria-hidden="true"
                title="FIT Library Instagram"></i><span class="sr-only">FIT Library Instagram</span></a></li>
          <li class="list-inline-item"><a class="link-dark" href="https://www.youtube.com/channel/UCtODQSjWRpZwy_pZYEgiBvw"
              aria-label="FIT Library YouTube"><i class="fab fa-youtube" aria-hidden="true"
                title="FIT Library YouTube"></i><span class="sr-only">FIT Library YouTube</span></a></li>

        </ul>
        <p class="text-left">
          <a href="https://www.fitnyc.edu/about/accessibility/issue-report.php">Report an Accessibility Issue</a>
        </p>
      </div>
    </div>
  </div>
</footer>
<?php echo $this->inlineScript(); ?>
</body>

</html>